# Generated by Django 3.1.6 on 2021-03-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
